### PR TITLE
runbooks: add runbook for Raffle

### PR DESCRIPTION
**Pull request by myitcv**

### CODE REVIEW

**Comment by myitcv** [comment]
@BryJamin - given you had to suffer this most recently... please can you review?

**Comment by myitcv** [comment]
>  sorry for the delay 

No apology needed! There's no time pressure on this stuff 😄 

> The only question is that when running through this myself I didn't know where the twitter API keys were, so should that be mentioned here or in the other wiki

Excellent point. I'll fix this tomorrow.

**Comment by myitcv** [comment]
@BryJamin - re-pushed with some notes on credentials.

https://github.com/LondonGophers/admin/blob/runbook_raffle/runbooks/raffle/README.md

Please can you give it a look?

**Comment by BryJamin** [comment]
Hiya, I don't think I have e-mail notifications on so totally missed the last comment. I've read over the new changes and they make sense and point to the correct location. So, I believe this is fine to merge in.

**Pull request merged**
